### ISSUE TITLE
Add support for setting person

### ISSUE THREAD

**Issue by sdhull** [paulcwatts/ember-cli-rollbar#29]
Thanks for working on this, it looks really promising! We just got our app deployed with fastboot and realized rollbar.js breaks

Anyway, Rollbar supports [people tracking](https://docs.rollbar.com/docs/person-tracking), which has come in handy for me in the past. Not really sure how this would work in this addon, but I guess it can just be configured on the rollbar instance?

**Comment by paulcwatts** [comment]
Hi @sdhull! You can definitely grab the instance off of the Rollbar service (inject the service, then do `this.get('rollbar.instance')`) and then call `configure()`. If you want to add an explicit method on the service, PRs are always appreciated.
