### ISSUE TITLE
Not sending source map.

### ISSUE THREAD

**Issue by williamweckl** [paulcwatts/ember-cli-rollbar#36]
Hi there. I've noticed that the library are not sending source maps as expected.

My environment.js config:
```
rollbar: {
      enabled: environment !== 'test' && environment !== 'development',
      captureUncaught: environment !== 'test',
      captureUnhandledRejections: environment !== 'test',
      accessToken: process.env.ROLLBAR_ACCESS_TOKEN,
      payload: {
        environment: process.env.ROLLBAR_ENV || environment,
        client: {
          javascript: {
            source_map_enabled: true,
            guess_uncaught_frames: true
          }
        }
      }
    },
    'ember-cli-rollbar': {
      captureEmberErrors: true,
      outputEmberErrorsToConsole: true,
      serverTokenEnv: 'ROLLBAR_SERVER_ACCESS_TOKEN'
}
```

Am I missing something?

**Comment by paulcwatts** [comment]
Hi @williamweckl!

You are correct, this addon doesn't upload sourcemaps to Rollbar. Uploading source maps should happen whenever you deploy your code.

First, make sure Ember is generating source maps by adding this to your `ember-cli-build.js`:

```js
  let app = new EmberApp(defaults, {
    sourcemaps: {
      enabled: true,
      extensions: ['js']
    }
  });
```

There are two ways Rollbar can use your sourcemaps: manually uploading them pre-deploy, or having Rollbar download them automatically. You can read more about that here: https://docs.rollbar.com/docs/source-maps/#section-providing-source-maps-to-rollbar

Uploading source maps is out of scope for this addon -- that would be better done using an ember-cli-deploy plugin (which I've considered writing, but I haven't gotten around to it). In my projects, I upload source maps manually using curl.

**Comment by acorncom** [comment]
@paulcwatts not sure if it helps you, but https://github.com/bgentry/ember-cli-deploy-rollbar-sourcemap is now a thing that might be useful for uploading your source maps
