### ISSUE TITLE
[setPerson bug] TypeError: this.instance.configure is not a function

### ISSUE THREAD

**Issue by bf4** [paulcwatts/ember-cli-rollbar#37]
Error points to the `setPerson` line from #33 

```es6
  setPerson(person) {
    return this.instance.configure({payload: {person}});
  }
```

I also wonder if `setPerson` should be defined in `init`.

My code is basically

```es6
import Base from 'ember-simple-auth/authenticators/base';
import { task } from 'ember-concurrency';
import { isPresent } from '@ember/utils';
import { inject as service } from '@ember/service';
//.....

export default Base.extend({
  authenticateTask: task(function * (accessToken) {
      //...
      this.set('sessionUser.userId', data.id);
      const rollbar = this.get('rollbar');
      if (isPresent(rollbar) && isPresent(data.id)) {
        try {
          rollbar.setPerson({"id": data.id, "name": data.attributes.name, "email": data.attributes["email-address"]});
        } catch(err) {
          rollbar.error('Unable to set user', err);
        }
      }
      //....
  }),
});
```

**Comment by bf4** [comment]
Related https://github.com/davewasmer/ember-cli-rollbar/issues/18 https://github.com/davewasmer/ember-cli-rollbar/blob/a51d933442221885b6058945b9ad1e27735357c8/tests/unit/utils/rollbar-global-test.js

**Comment by paulcwatts** [comment]
Is the error happening in dev builds? What version of rollbar are you using?

My suspicion is that you're running into this in a dev build. In those cases, rollbar isn't included but should be stubbed with console methods, here: https://github.com/paulcwatts/ember-cli-rollbar/blob/master/addon/services/rollbar.js#L22

It appears that we missed adding `configure` to this list. If this is the case, then it's an easy fix to make.

**Comment by bf4** [comment]
I am indeed experiencing this in development mode.  Even though rollbar isn't included, I am seeing `window.Rollbar` is being present. So, I guess that's what surprised me. 

Setting `ENV['rollbar'].enabled = true` seems sufficient.

For now I changed my conditional to

```es6
      if (isPresent(rollbar) && isPresent(data.id) && isPresent(rollbar.instance.configure)) {
```

**Comment by bf4** [comment]
Made a PR :) https://github.com/paulcwatts/ember-cli-rollbar/pull/38
